version: "3"
services:
  db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres:latest"
    #   Give the container the name my_postgres. You can change to something else.
    container_name: "blogit_db"
    #   Setup the username, password, and database name. You can change these values.
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogit
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:

