spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogit
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    locations:
      - classpath:db/migration
    enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8083
